/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package adj.felix.hadoop.pojo;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Data extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Data\",\"namespace\":\"adj.felix.hadoop.pojo\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"age\",\"type\":[\"int\",\"null\"]},{\"name\":\"info\",\"type\":[\"string\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence name;
  @Deprecated public java.lang.Integer age;
  @Deprecated public java.lang.CharSequence info;

  /**
   * Default constructor.
   */
  public Data() {}

  /**
   * All-args constructor.
   */
  public Data(java.lang.CharSequence name, java.lang.Integer age, java.lang.CharSequence info) {
    this.name = name;
    this.age = age;
    this.info = info;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return age;
    case 2: return info;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    case 1: age = (java.lang.Integer)value$; break;
    case 2: info = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'age' field.
   */
  public java.lang.Integer getAge() {
    return age;
  }

  /**
   * Sets the value of the 'age' field.
   * @param value the value to set.
   */
  public void setAge(java.lang.Integer value) {
    this.age = value;
  }

  /**
   * Gets the value of the 'info' field.
   */
  public java.lang.CharSequence getInfo() {
    return info;
  }

  /**
   * Sets the value of the 'info' field.
   * @param value the value to set.
   */
  public void setInfo(java.lang.CharSequence value) {
    this.info = value;
  }

  /** Creates a new Data RecordBuilder */
  public static adj.felix.hadoop.pojo.Data.Builder newBuilder() {
    return new adj.felix.hadoop.pojo.Data.Builder();
  }
  
  /** Creates a new Data RecordBuilder by copying an existing Builder */
  public static adj.felix.hadoop.pojo.Data.Builder newBuilder(adj.felix.hadoop.pojo.Data.Builder other) {
    return new adj.felix.hadoop.pojo.Data.Builder(other);
  }
  
  /** Creates a new Data RecordBuilder by copying an existing Data instance */
  public static adj.felix.hadoop.pojo.Data.Builder newBuilder(adj.felix.hadoop.pojo.Data other) {
    return new adj.felix.hadoop.pojo.Data.Builder(other);
  }
  
  /**
   * RecordBuilder for Data instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Data>
    implements org.apache.avro.data.RecordBuilder<Data> {

    private java.lang.CharSequence name;
    private java.lang.Integer age;
    private java.lang.CharSequence info;

    /** Creates a new Builder */
    private Builder() {
      super(adj.felix.hadoop.pojo.Data.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(adj.felix.hadoop.pojo.Data.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing Data instance */
    private Builder(adj.felix.hadoop.pojo.Data other) {
            super(adj.felix.hadoop.pojo.Data.SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.age)) {
        this.age = data().deepCopy(fields()[1].schema(), other.age);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.info)) {
        this.info = data().deepCopy(fields()[2].schema(), other.info);
        fieldSetFlags()[2] = true;
      }
    }

    /** Gets the value of the 'name' field */
    public java.lang.CharSequence getName() {
      return name;
    }
    
    /** Sets the value of the 'name' field */
    public adj.felix.hadoop.pojo.Data.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'name' field has been set */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'name' field */
    public adj.felix.hadoop.pojo.Data.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'age' field */
    public java.lang.Integer getAge() {
      return age;
    }
    
    /** Sets the value of the 'age' field */
    public adj.felix.hadoop.pojo.Data.Builder setAge(java.lang.Integer value) {
      validate(fields()[1], value);
      this.age = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'age' field has been set */
    public boolean hasAge() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'age' field */
    public adj.felix.hadoop.pojo.Data.Builder clearAge() {
      age = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'info' field */
    public java.lang.CharSequence getInfo() {
      return info;
    }
    
    /** Sets the value of the 'info' field */
    public adj.felix.hadoop.pojo.Data.Builder setInfo(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.info = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'info' field has been set */
    public boolean hasInfo() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'info' field */
    public adj.felix.hadoop.pojo.Data.Builder clearInfo() {
      info = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public Data build() {
      try {
        Data record = new Data();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.age = fieldSetFlags()[1] ? this.age : (java.lang.Integer) defaultValue(fields()[1]);
        record.info = fieldSetFlags()[2] ? this.info : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
